### ISSUE TITLE
PushNotifications

### ISSUE THREAD

**Issue by JurajPupak** [Microsoft/WebRTC-universal-samples#3]
Could you please explain the purpose of PushNotification in this app? All activity is done through SocketActivityTrigger. It would be fine, if you provide some explanation how to simulate push notifications. 
Thank you

**Comment by jamescadd** [comment]
Hello,

SocketActivityTrigger was used to perform notifications so that the app has more full control over when to notify the user, rather than putting that burden on the server.  It also allows the background process to wake and begin initiating a connection during a video call immediately.  This improves the user experience by reducing the amount of time between when a user accepts a call and when a video feed begins.

Thanks,
James
