### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by niklaswolf** [Microsoft/WebRTC-universal-samples#8]
Hi, I want to use this library in an Hololens-Application to implement Voice-Chat, but I can't find any documentation on how to use it.
The Chatter-Box example is very complicated to get behind in my opinion, especially when you don't know where to start to have a look at.
So do you have any pointers/ am I failing to find the docs?

**Comment by jamescadd** [comment]
Hi Niklas, we're deprecating the ChatterBox sample for the reason that you've mentioned.  It will remain as a VoIP implementation sample for those requiring it, but our focus will be on PeerConnection.  This sample has issues today on HoloLens due to poor performance caused by the Chrome codebase that's currently in release.  We're nearing completion on a merge with Chrome M58 which resolves these issues, and an updated PeerConnection will be posted in the coming weeks when the work is completed.  Fair criticism on the documentation, I'll work on that.  In the meantime let me know if there's anything in particular you need.

**Comment by jamescadd** [comment]
Here's a link to the PeerCC sample.  Unfortunately we don't have documentation but the code is much more straightforward than Chatterbox.  If you have any questions please reach out to me at jacadd@microsoft.com and we'll get them answered.

https://github.com/Microsoft/WebRTC-universal-samples/tree/master/Samples/PeerCC-Sample
